name: booking_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  device_preview: ^1.1.0
  flutter_native_splash: ^2.3.1
  flutter:
    sdk: flutter

  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/google.png
  android_12:
    color: "#ffffff"
    image: assets/google.png

  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/facebook.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Group.png
    - assets/google.png
    - assets/facebook.png
    - assets/first_image.png
    - assets/second_image.png
    - assets/third_image.png
    - assets/background/blur_effect.png
    - assets/background/small_blur_effect.png
