name: booking_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  device_preview: ^1.1.0
  flutter_native_splash: ^2.3.1
  flutter:
    sdk: flutter

  get: ^4.6.5
  cupertino_icons: ^1.0.6
  readmore: ^2.2.0
  flutter_bloc: ^8.1.4
  go_router: ^13.2.0
  flutter_secure_storage: ^4.2.1
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/google.png
  android_12:
    color: "#ffffff"
    image: assets/google.png

  android: true
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/facebook.png"

flutter:
  uses-material-design: true
  assets:
    - assets/image/Group.png
    - assets/image/google.png
    - assets/image/facebook.png
    - assets/image/first_image.png
    - assets/image/second_image.png
    - assets/image/third_image.png
    - assets/image/background/blur_effect.png
    - assets/image/background/small_blur_effect.png
    - assets/image/home/menu_icon.png
    - assets/image/home/user.png
    - assets/image/home/user2.png
    - assets/image/home/pro_icon.png
    - assets/image/home/date.png
    - assets/image/home/pin_map.png
    - assets/image/home/invite_friend.png
    - assets/image/home/events/event1.png
    - assets/image/home/events/event2.png
    - assets/image/home/events/event3.png
    - assets/image/home/events/event4.png
    - assets/image/home/events/event5.png
    - assets/image/home/events/event6.png
    - assets/image/home/events/event7.png
    - assets/image/home/events/event8.png
    - assets/image/home/events/person1.png
    - assets/image/home/events/person2.png
    - assets/image/home/events/person3.png
    - assets/image/home/events/pin.png
    - assets/image/home/events/organizer.png
    - assets/image/events/no_event_image.png
    - assets/image/events/notif.png

  fonts:
    - family: AirbnbCereal
      fonts:
        - asset: assets/font/AirbnbCereal_W_Bd.otf
        - asset: assets/font/AirbnbCereal_W_Bk.otf
        - asset: assets/font/AirbnbCereal_W_Blk.otf
        - asset: assets/font/AirbnbCereal_W_Lt.otf
        - asset: assets/font/AirbnbCereal_W_Md.otf
        - asset: assets/font/AirbnbCereal_W_XBd.otf
